name: Minefetch
version: '2.3.2'
main: ru.uwuocha.minefetch.Minefetch
api-version: '1.21'
author: uwuocha
description: "Плагин для отображения информации о сервере в стиле neofetch"
website: "https://github.com/UwUOcha/minefetch"

permissions:
  minefetch.use:
    description: "Разрешение на использование команды /minefetch"
    default: true
  minefetch.reload:
    description: "Разрешение на перезагрузку конфигурации"
    default: op
