name: Minefetch
version: '2.5.0'
main: ru.uwuocha.minefetch.Minefetch
api-version: '1.21'
author: uwuocha
description: "Plugin for displaying server information in neofetch style"
website: "https://github.com/UwUOcha/minefetch"

permissions:
  minefetch.use:
    description: "Permission to use the /minefetch command"
    default: true
  minefetch.reload:
    description: "Permission to reload the configuration"
    default: op
