# Имя вашего плагина
name: Minefetch
# Версия плагина
version: '2.0.0'
# Главный класс, который будет загружен
main: ru.uwuocha.minefetch.Minefetch
# Версия API сервера, для которой написан плагин
api-version: '1.21'
# Автор плагина
author: uwuocha
# Описание
description: "Плагин для отображения информации о сервере в стиле neofetch"
# Веб-сайт
website: "https://github.com/uwuocha/minefetch"

# Регистрация прав доступа
permissions:
  minefetch.use:
    description: "Разрешение на использование команды /minefetch"
    default: true
  minefetch.reload:
    description: "Разрешение на перезагрузку конфигурации"
    default: op