# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Plugin CI (Gradle)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle' 

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew 

    - name: Build with Gradle
      run: ./gradlew build 

    - name: Upload Plugin Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MyMinecraftPlugin
        path: build/libs/*.jar 
